### ISSUE TITLE
Is this a fuzzy Neural Network?

### ISSUE THREAD

**Issue by sprtkd** [ameybarapatre/ANFIS#1]
Is this a fuzzy neural network implementation using tensorflow???
Working on a similar project so will be very helpful to know.

**Comment by ameybarapatre** [comment]
Yes , Look at ANFIS.py file  , Q learning is used to train the network . Anyway look at line 29 , Q is the total output of the network. Prerocessing.py file is used to calculate membership values . Rules are mentioned in  rules.txt

**Comment by sprtkd** [comment]
Thanks.. Just needed a suggestion. Can we apply these fuzzy rules to cnns and rnns too?

**Comment by ameybarapatre** [comment]
https://www.researchgate.net/publication/3855330_Fuzzy_Reasoning_for_the_design_of_CNN-based_image_processing_systems
