### ISSUE TITLE
Error in anfis.py and run.py

### ISSUE THREAD

**Issue by javej** [ameybarapatre/ANFIS#2]
for anfis.py
TypeError                                 Traceback (most recent call last)
<ipython-input-15-326b994fc4fe> in <module>()
     63 
     64 if __name__=="__main__" :
---> 65     E = taxi_eligibility([[0.4216668178867803,0.32799309442505115,0.7501831501831502,0.8334689890932769]])
     66     #E = taxi_eligibility([[taxi,taxis_y ,alpha ,Gamma]])
     67     print(E ,"Done Here")

TypeError: taxi_eligibility() missing 3 required positional arguments: 'taxis_y', 'alpha', and 'Gamma'

for run.py
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-9dea64d14a8b> in <module>()
      1 #run.py
      2 
----> 3 import anfis
      4 import pandas as pd
      5 import numpy as np

~\Anaconda3\envs\tensorflow\lib\site-packages\anfis\__init__.py in <module>()
      1 import anfis
----> 2 from membership import membershipfunction
      3 from membership import mfDerivs

ModuleNotFoundError: No module named 'membership'

any help on how to fix these errors?

**Comment by ameybarapatre** [comment]
taxi_eligibility([[0.4216668178867803,0.32799309442505115,0.7501831501831502,0.8334689890932769]]) 
 that's a 2D array,  so you might wanna send the parameters normally or as '*array_name' for a 1D array.

**Comment by JaveJao** [comment]
ohhhhh. how about the 'no module named membership' errror? how do I fix that?

**Comment by javej** [comment]
forgive me but I'm really just a newbie here. how do I send the parameters normally? why does it point to 'taxis_y', 'alpha', and 'Gamma' as missing arguments?

**Comment by ameybarapatre** [comment]
normally in the sense, taxis_y = value , apha = value. Why it points to the rest as the missing arguments as it took the array as the first argument.

**Comment by javej** [comment]
how do I retype this code to fix it?
if __name__=="__main__" :
    E = taxi_eligibility([[0.4216668178867803,0.32799309442505115,0.7501831501831502,0.8334689890932769]])
    print(E ,"Done Here")

**Comment by ameybarapatre** [comment]
refer to run.py

**Comment by Uditi5** [comment]
How did you fix the Module not found error ?
